language: python
python:
  - '3.5'
install:
  - 'pip install -r requirements.txt'
  - 'python -m nltk.downloader "stopwords"'
script: 'python -m unittest'
after_success:
  - './test_coverage.sh'
cache:
  pip: true 
  directories:
  - $HOME/nltk_data
